from unicodedata import name
from venv import create
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from Main.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('get-info/', Getinfo),
    path('get-slider/', Getslider),
    path('get-projects/', Getprojects),
    path('get-technopark/', Gettechnopark),
    path('get-section/<int:pk>/', Getsection),
    path('get-postalservices/', Getpostal),
    path('get-boglanish', Getboglanish),
    path('get-mobileoperators/', Getmobileoperators),
    path('get-internetproviders/', Getinternetproviders),
    path('get-ouraudience/', Getouraudience),
    path('get-percentage/', Getpercentage),
    path('get-residents/', Getresidents),
    path('get-team/', Getteam),
    path('get-coimages/', Getcoimages),
    path('get-coworking/', Getcoworking),
    path('get-infrastructure/', Getinfrastructure),
    path('get-studydirections/', Getstudydirections),
    path('get-itacademy/', Getitacademy),
    path('get-startupdirections/', Getstartupdirections),
    path('get-incubationcenters/', Getincubationcenters),
    path('get-raqamlashtirishxizmatlari/', Getraqamlashtirish),
    path('post-contact/', Getcontact),
    path('get-xizmatturi/', Getxizmatturi),
    path('get-xizmatlar/', Getxizmatlar),
    path('get-application', Getapplication),
    #### 


    path('', Index, name='index'),
    path('section/', Section_funk, name='Section'),
    path('info/',Info_funk,name='info'),
    path('slider/', Slider_funk,name='Slider'),
    path('project/', Projects_funk,name='Project'),
    path('technopark/', Technopark_funk,name='Technopark'),
    path('postalservices/', Postal_Services,name='PostalServices'),
    path('boglanish/', Boglanish_Funk,name='Boglanish'),
    path('mobileoperators/', Mobileoperators_Funk,name='Mobileoperators'),
    path('internetproviders/', Internetproviders_Funk,name='Internetproviders'),
    path('ourAudience/', OurAudience_Funk,name='OurAudience'),
    path('percentage/', Percentage_Funk,name='Percentage'),
    path('residents/', Residents_Funk,name='Residents'),
    path('team/', Team_Funk,name='Team'),
    path('coimages/', Coimages_Funk,name='Coimages'),
    path('coworking/', Coworking_Funk,name='Coworking'),
    path('InfrastructureSlider/', InfrastructureSlider_Funk,name='InfrastructureSlider'),
    path('studyDirections/', StudyDirections_Funk,name='StudyDirections'),
    path('itAcademy/', ItAcademy_Funk,name='ItAcademy'),
    path('startupDirections/', StartupDirections_Funk,name='StartupDirections'),
    path('IncubationCenters/', IncubationCenters_Funk,name='IncubationCenters'),
    path('contact/', Contact_Funk,name='Contact'),
    path('xizmatTuri/', XizmatTuri_Funk,name='XizmatTuri'),
    path('xizmatlar/', Xizmatlar_Funk,name='Xizmatlar'),
    path('application/', Application_Funk,name='Application'),
    path('raqamlashtirishxizmatlari/', Raqamlashtirishxizmatlari_Funk,name='Raqamlashtirishxizmatlari'),
    
    
    
    path('change-info/<int:pk>/', Change_Info, name='change-info'),
    path('change-slider/', Change_Slider, name='change-slider'),
    path('change-project/', Change_Project, name='change-project'),
    path('change-technopark/', Change_Technopark, name='change-technopark'),
    path('change-section/', Change_Section, name='change-section'),
    path('change-postalservice/', Change_PostalServices, name='change-postalservices'),
    path('change-mobileoperators', Change_MobileOperators, name='change-mobileoperators'),
    path('change-internetproviders', Change_InternetProviders, name='change-internetproviders'),


    path('delete-boglanish/<int:pk>/', deletebooglanish,name='deleteboglanish'),
    path('delete-info/<int:pk>', DeleteInfo, name='delete-info'),
    path('delete-info/<int:pk>/', DeleteInfo, name='delete-info'),
    path('delete-slider/<int:pk>/', DeleteSlider, name='delete-slider'),
    path('delete-project/<int:pk>', DeleteProject, name='delete-project'),
    path('delete-technopark/<int:pk>', DeleteTechnopark, name='delete-technopark'),
    path('delete-section/<int:pk>', DeleteSection, name='delete-section'),
    path('delete-postalservices/<int:pk>', DeletePostalServices, name='delete-postalservices'),
    path('delete-mobileoperators/<int:pk>', DeleteMobileOperators, name='delete-mobileoperators'),
    path('delete-internetproviders/<int:pk>', DeleteInternetproviders, name='delete-internetproviders'),
    path('delete-ouraudience/<int:pk>', DeleteOurAudience, name='delete-ouraudience'),
    path('delete-percentage/<int:pk>', DeletePercentage, name='delete-percentage'),
    path('delete-residents/<int:pk>', DeleteResidents, name='delete-residents'),
    path('delete-team/<int:pk>', DeleteTeam, name='delete-team'),
    path('delete-coimages/<int:pk>', DeleteCoimages, name='delete-coimages'),
    path('delete-coworking/<int:pk>', DeleteCoworking, name='delete-coworking'),
    path('delete-InfrastructureSlider/<int:pk>', DeleteInfrastructureSlider, name='delete-infrastructureslider'),
    path('delete-studyDirections/<int:pk>', DeleteStudyDirections, name='delete-studyDirections'),
    path('delete-ItAcademy/<int:pk>', DeleteItAcademy, name='delete-ItAcademy'),
    path('delete-startupDirections/<int:pk>', DeleteStartupDirections, name='delete-startupDirections'),
    path('delete-incubationcenters/<int:pk>', DeleteIncubationCenters, name='delete-incubationcenters'),
    path('delete-raqamlashtirishxizmatlari/<int:pk>', DeleteRaqamlashtirishxizmatlari, name='delete-raqamlashtirishxizmatlari'),
    path('delete-contact/<int:pk>', DeleteContact, name='delete-contact'),
    path('delete-xizmatturi/<int:pk>', DeleteXizmatTuri, name='delete-xizmatturi'),
    path('delete-Xizmatlar/<int:pk>', DeleteXizmatlar, name='delete-Xizmatlar'),
    path('delete-application/<int:pk>', DeleteApplication, name='delete-application'),
    path('delete-studyDirections/<int:pk>', DeleteStudyDirections, name='delete-studydirections'),
    path('delete-itAcademy/<int:pk>', DeleteItAcademy, name='delete-itAcademy'),



    path('info-create',InfoCreate_Funk,name='info-create'),
    path('slider-create',SliderCreate_Funk,name='slider-create'),
    path('projects-create',ProjectsCreate_Funk,name='projects-create'),
    path('create-technopark',TechnoparkCreate_Funk,name='technopark-create'),
    path('create-section',SectionCreate_Funk,name='section-create'),
    path('create-postalservices',PostalserviceCreate_Funk,name='postal_create'),
    path('create-boglanish',MobilCreate_Funk,name='mobil-create'),
    path('create-internetproviders',InternetprovidersCreate_Funk,name='internetprovider-create'),
    path('create_ouraudience',OurAudienceCreate_Funk,name='ouraudience-create'),
    path('create-percentage',PercentageCreate_Funk,name='percentage-create'),
    path('create-residents',ResidentsCreate_Funk,name='resident-create'),
    path('create-team',CreateTeam_funk,name='team-create'),
    path('create-coimages',CreateCoimages_Funk,name='coimages-create'),
    path('create-coworking',CoworkingCreate_Funk,name='coworking-create'),
    path('create-instruction',CreateInfrastructureCreate_Funk,name='instruction-create'),
    path('create-studyDirections',CreateStudyDirections_Funk,name='StudyDirections-create'),
    path('create-itacademy', CreateItAcademy,name='itacademy-create'),
    path('create-startup',CreateStartUp,name='startup-create'),
    path('create-incubationcenters',CreateIncubationCenters,name='incubationcenters-create'),
    path('create-raqamlashtirishxizmatlari',CreateRaqamlashtirish,name='raqamlashtirishxizmatlari-create'),
    path('create-xizmatlar',CreateXizmatlar,name='xizmatlar-create'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
